# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2086e4f8834154039791a67ddcaf364e7af6e09dadfa6ef7aee73ba5c64b4d776e2d5d33700bb748fc113aa37425a0deea73f12b0a5e2d8b7e6aa9008e184b6

test:
  secret_key_base: 8ae7452bc33698fc058d07d94cf59581cdcfce1f9cd119c1047f6e6105217a41671a7ac96b074691072d427280665cf5a7decb146297b5576ecf8f5a00d83384

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
